version: "3.7"
services:
  neo4j-family-tree:
    image: neo4j:5-enterprise
    restart: unless-stopped
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4j_AUTH=${FAMILY_TREE_DB_USERNAME}/${FAMILY_TREE_DB_PASSWORD}
    volumes:
      - db-family-tree:/data
    networks:
      - family-tree
  mongodb-user:
    image: mongo:6.0.4
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USER_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${USER_DB_PASSWORD}
    volumes:
      - db-user:/data/db
    networks:
      - user
  mongodb-private-chat:
    image: mongo:6.0.4
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${PRIVATE_CHAT_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PRIVATE_CHAT_DB_PASSWORD}
    volumes:
      - db-private-chat:/data/db
    networks:
      - private-chat
  mongodb-public-chat:
    image: mongo:6.0.4
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${PUBLIC_CHAT_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PUBLIC_CHAT_DB_PASSWORD}
    volumes:
      - db-public-chat:/data/db
    networks:
      - public-chat
  user-service:
    image:
      kacperkruger/tsw-user-service:latest
    restart: unless-stopped
    environment:
      - PORT=4000
      - MONGO_HOST=mongodb-user
      - MONGO_PORT=27017
      - MONGO_USER=${USER_DB_USERNAME}
      - MONGO_PASS=${USER_DB_PASSWORD}
    depends_on:
      - mongodb-user
    networks:
      - user
  private-chat-service:
    image:
      kacperkruger/tsw-private-chat-service:latest
    restart: unless-stopped
    environment:
      - PORT=5000
      - MONGO_HOST=mongodb-private-chat
      - MONGO_PORT=27017
      - MONGO_USER=${PRIVATE_CHAT_DB_USERNAME}
      - MONGO_PASS=${PRIVATE_CHAT_DB_PASSWORD}
    depends_on:
      - mongodb-private-chat
    networks:
      - private-chat
  public-chat-service:
    image:
      kacperkruger/tsw-public-chat-service:latest
    restart: unless-stopped
    environment:
      - PORT=6000
      - MONGO_PORT=27017
      - MONGO_HOST=mongodb-public-chat
      - MONGO_USER=${PUBLIC_CHAT_DB_USERNAME}
      - MONGO_PASS=${PUBLIC_CHAT_DB_PASSWORD}
    depends_on:
      - mongodb-public-chat
    networks:
      - public-chat
  family-tree-service:
    image: kacperkruger/tsw-family-tree-service:latest
    restart: unless-stopped
    environment:
      - PORT=7000
      - NEO4J_URI=bolt://neo4j-family-tree/7687
      - NEO4J_USER=${FAMILY_TREE_DB_USERNAME}
      - NEO4J_PASSWORD=${FAMILY_TREE_DB_PASSWORD}
    depends_on:
      - neo4j-family-tree
    networks:
      - family-tree
  websocket-service:
    image: kacperkruger/tsw-websocket-service:latest
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      - PORT=9000
      - WEB_CLIENT_HOST_URL=http://localhost
    networks:
      - websocket
  api-gateway-service:
    image: kacperkruger/tsw-api-gateway:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - JWT_SECRET=${JWT_SECRET}
      - USER_SERVICE_HOST_URL=http://user-service:4000
      - PRIVATE_CHAT_SERVICE_HOST_URL=http://private-chat-service:5000
      - PUBLIC_CHAT_SERVICE_HOST_URL=http://public-chat-service:6000
      - FAMILY_TREE_SERVICE_HOST_URL=http://family-tree-service:7000
      - WEB_CLIENT_HOST_URL=http://localhost
    depends_on:
      - family-tree-service
      - public-chat-service
      - private-chat-service
      - user-service
    networks:
      - api-gateway
      - public-chat
      - private-chat
      - user
      - family-tree
  webclient-service:
    image: kacperkruger/tsw-webclient-service:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api-gateway-service
      - websocket-service
    networks:
      - api-gateway
      - websocket

networks:
  public-chat:
    driver: bridge
  private-chat:
    driver: bridge
  user:
    driver: bridge
  family-tree:
    driver: bridge
  websocket:
    driver: bridge
  api-gateway:
    driver: bridge

volumes:
  db-user:
  db-family-tree:
  db-private-chat:
  db-public-chat: