version: "3.7"
services:
  neo4j-family-tree:
    image: neo4j:5-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4j_AUTH=${FAMILY_TREE_DB_USERNAME}/${FAMILY_TREE_DB_PASSWORD}
    volumes:
      - db-family-tree:/data
    networks:
      - family-tree
  mongodb-user:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USER_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${USER_DB_PASSWORD}
    volumes:
      - db-user:/data/db
    networks:
      - user
  mongodb-private-chat:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${PRIVATE_CHAT_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PRIVATE_CHAT_DB_PASSWORD}
    volumes:
      - db-private-chat:/data/db
    networks:
      - private-chat
  mongodb-public-chat:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${PUBLIC_CHAT_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PUBLIC_CHAT_DB_PASSWORD}
    volumes:
      - db-public-chat:/data/db
    networks:
      - public-chat
  user-service:
    image:
      kacperkruger/tsw-user-service:latest
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_HOST=mongodb-user
      - MONGO_PORT=27017
      - MONGO_USER=${USER_DB_USERNAME}
      - MONGO_PASS=${USER_DB_PASSWORD}
    depends_on:
      - mongodb-user
    networks:
      - user
  private-chat-service:
    image:
      kacperkruger/tsw-private-chat-service:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_HOST=mongodb-private-chat
      - MONGO_PORT=27017
      - MONGO_USER=${PRIVATE_CHAT_DB_USERNAME}
      - MONGO_PASS=${PRIVATE_CHAT_DB_PASSWORD}
    depends_on:
      - mongodb-private-chat
    networks:
      - private-chat
  public-chat-service:
    image:
      kacperkruger/tsw-public-chat-service:latest
    ports:
      - "6000:6000"
    environment:
      - PORT=6000
      - MONGO_PORT=27017
      - MONGO_HOST=mongodb-public-chat
      - MONGO_USER=${PUBLIC_CHAT_DB_USERNAME}
      - MONGO_PASS=${PUBLIC_CHAT_DB_PASSWORD}
    depends_on:
      - mongodb-public-chat
    networks:
      - public-chat
  family-tree-service:
    image: kacperkruger/tsw-family-tree-service:latest
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - NEO4J_URI=bolt://neo4j-family-tree/7687
      - NEO4J_USER=${FAMILY_TREE_DB_USERNAME}
      - NEO4J_PASSWORD=${FAMILY_TREE_DB_PASSWORD}
    depends_on:
      - neo4j-family-tree
    networks:
      - family-tree

networks:
  public-chat:
    driver: bridge
  private-chat:
    driver: bridge
  user:
    driver: bridge
  family-tree:
    driver: bridge

volumes:
  db-user:
  db-family-tree:
  db-private-chat:
  db-public-chat: